function result = classify_pipe_signal( ...
    windowFeatures, ...
    thresholds)
%CLASSIFY_PIPE_SIGNAL
%
% Classifies one full signal using:
%
% 1. RMS threshold
% 2. Leak-band energy-ratio threshold
% 3. Spectral-centroid threshold
%
% A window is leak-like when at least two of the three features exceed
% their thresholds.
%
% A full signal is classified as a sustained leak when the required
% percentage of its windows are leak-like.

    %% Compare every feature against its threshold

    rmsFlag = ...
        windowFeatures.RMS >= thresholds.rms;

    energyRatioFlag = ...
        windowFeatures.EnergyRatio >= thresholds.energyRatio;

    spectralCentroidFlag = ...
        windowFeatures.SpectralCentroid >= ...
        thresholds.spectralCentroid;

    %% Count positive feature votes in each window

    featureVoteCount = ...
        double(rmsFlag) + ...
        double(energyRatioFlag) + ...
        double(spectralCentroidFlag);

    %% Determine which windows appear leak-like

    positiveWindow = ...
        featureVoteCount >= thresholds.minimumFeatureVotes;

    %% Calculate persistence

    persistence = mean(positiveWindow);

    %% Full-signal leak decision

    predictedLeak = ...
        persistence >= thresholds.minimumPersistence;

    %% Assign descriptive result

    if predictedLeak

        classification = "Probable sustained leak";

    elseif any(positiveWindow)

        classification = "Possible intermittent event";

    else

        classification = "Normal or non-leak event";
    end

    %% Return decision results

    result = struct( ...
        'PredictedLeak', ...
            predictedLeak, ...
        'Classification', ...
            classification, ...
        'Persistence', ...
            persistence, ...
        'MeanVoteCount', ...
            mean(featureVoteCount), ...
        'MaximumVoteCount', ...
            max(featureVoteCount), ...
        'RMSFlagRate', ...
            mean(rmsFlag), ...
        'EnergyFlagRate', ...
            mean(energyRatioFlag), ...
        'SpectralCentroidFlagRate', ...
            mean(spectralCentroidFlag));
end