function [summary, windowFeatures] = extract_pipe_features( ...
    signal, ...
    fs, ...
    settings)
%EXTRACT_PIPE_FEATURES
%
% Extracts windowed time-domain and frequency-domain features from one
% vibration signal.
%
% Inputs:
%   signal   - one pipe vibration signal
%   fs       - sampling frequency in Hz
%   settings - structure containing analysis settings
%
% Outputs:
%   summary        - signal-level average feature values
%   windowFeatures - feature values for every analysis window

    signal = double(signal(:).');

    %% Remove signal DC offset

    signal = signal - mean(signal);

    %% Calculate window parameters

    windowLength = round( ...
        settings.windowSeconds * fs);

    windowLength = max(windowLength, 16);

    hopLength = round( ...
        windowLength * (1 - settings.windowOverlap));

    hopLength = max(hopLength, 1);

    %% Zero-pad short signals

    if length(signal) < windowLength

        requiredPadding = windowLength - length(signal);

        signal = [
            signal, ...
            zeros(1, requiredPadding)
        ];
    end

    %% Determine window start positions

    windowStarts = 1:hopLength: ...
        (length(signal) - windowLength + 1);

    numberOfWindows = length(windowStarts);

    %% Initialize feature table

    windowFeatures = table( ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        zeros(numberOfWindows, 1), ...
        'VariableNames', { ...
            'RMS', ...
            'Variance', ...
            'MeanAbsoluteValue', ...
            'CrestFactor', ...
            'ZeroCrossingRate', ...
            'EnergyRatio', ...
            'SpectralCentroid', ...
            'DominantFrequency', ...
            'StartTime'});

    %% Process every signal window

    for windowIndex = 1:numberOfWindows

        startIndex = windowStarts(windowIndex);

        endIndex = startIndex + windowLength - 1;

        currentWindow = signal(startIndex:endIndex);

        currentWindow = currentWindow - mean(currentWindow);

        %% Bandpass filter

        filteredWindow = fft_bandpass_filter( ...
            currentWindow, ...
            fs, ...
            settings.analysisBandHz);

        %% Time-domain features

        rmsValue = sqrt( ...
            mean(filteredWindow.^2));

        varianceValue = mean( ...
            (filteredWindow - mean(filteredWindow)).^2);

        meanAbsoluteValue = mean( ...
            abs(filteredWindow));

        peakValue = max( ...
            abs(filteredWindow));

        crestFactor = peakValue / max(rmsValue, eps);

        %% Zero-crossing rate

        signalSigns = sign(filteredWindow);

        signalSigns(signalSigns == 0) = 1;

        numberOfZeroCrossings = sum( ...
            signalSigns(1:end-1) ~= signalSigns(2:end));

        zeroCrossingRate = numberOfZeroCrossings / ...
            max(length(signalSigns) - 1, 1);

        %% Apply Hann window before FFT

        numberOfSamples = length(filteredWindow);

        sampleNumbers = 0:numberOfSamples-1;

        hannWindow = 0.5 - ...
            0.5 * cos( ...
                2 * pi * sampleNumbers / ...
                max(numberOfSamples - 1, 1));

        windowedSignal = filteredWindow .* hannWindow;

        %% Calculate positive-frequency power spectrum

        spectrum = fft(windowedSignal);

        numberPositiveBins = floor(numberOfSamples / 2) + 1;

        positiveSpectrum = spectrum(1:numberPositiveBins);

        frequencyAxis = ...
            (0:numberPositiveBins - 1) * fs / numberOfSamples;

        powerSpectrum = abs(positiveSpectrum).^2;

        %% Create frequency masks

        analysisFrequencyMask = ...
            frequencyAxis >= settings.analysisBandHz(1) & ...
            frequencyAxis <= settings.analysisBandHz(2);

        leakFrequencyMask = ...
            frequencyAxis >= settings.leakBandHz(1) & ...
            frequencyAxis <= settings.leakBandHz(2);

        %% Leak-band energy ratio

        totalBandPower = sum( ...
            powerSpectrum(analysisFrequencyMask));

        leakBandPower = sum( ...
            powerSpectrum(leakFrequencyMask));

        energyRatio = leakBandPower / ...
            max(totalBandPower, eps);

        %% Spectral centroid

        analysisPower = ...
            powerSpectrum(analysisFrequencyMask);

        analysisFrequencies = ...
            frequencyAxis(analysisFrequencyMask);

        spectralCentroid = sum( ...
            analysisFrequencies .* analysisPower) / ...
            max(sum(analysisPower), eps);

        %% Dominant frequency

        [~, dominantFrequencyIndex] = max(analysisPower);

        dominantFrequency = ...
            analysisFrequencies(dominantFrequencyIndex);

        %% Save window features

        windowFeatures.RMS(windowIndex) = rmsValue;

        windowFeatures.Variance(windowIndex) = ...
            varianceValue;

        windowFeatures.MeanAbsoluteValue(windowIndex) = ...
            meanAbsoluteValue;

        windowFeatures.CrestFactor(windowIndex) = ...
            crestFactor;

        windowFeatures.ZeroCrossingRate(windowIndex) = ...
            zeroCrossingRate;

        windowFeatures.EnergyRatio(windowIndex) = ...
            energyRatio;

        windowFeatures.SpectralCentroid(windowIndex) = ...
            spectralCentroid;

        windowFeatures.DominantFrequency(windowIndex) = ...
            dominantFrequency;

        windowFeatures.StartTime(windowIndex) = ...
            (startIndex - 1) / fs;
    end

    %% Create signal-level summary

    summary = struct( ...
        'MeanRMS', ...
            mean(windowFeatures.RMS), ...
        'StandardDeviationRMS', ...
            std(windowFeatures.RMS), ...
        'MeanVariance', ...
            mean(windowFeatures.Variance), ...
        'MeanAbsoluteValue', ...
            mean(windowFeatures.MeanAbsoluteValue), ...
        'MeanCrestFactor', ...
            mean(windowFeatures.CrestFactor), ...
        'MeanZeroCrossingRate', ...
            mean(windowFeatures.ZeroCrossingRate), ...
        'MeanEnergyRatio', ...
            mean(windowFeatures.EnergyRatio), ...
        'MeanSpectralCentroid', ...
            mean(windowFeatures.SpectralCentroid), ...
        'MeanDominantFrequency', ...
            mean(windowFeatures.DominantFrequency), ...
        'NumberOfWindows', ...
            height(windowFeatures));
end