function plot_signal_diagnostics( ...
    signal, ...
    fs, ...
    signalLabel, ...
    windowFeatures, ...
    thresholds, ...
    settings)
%PLOT_SIGNAL_DIAGNOSTICS
%
% Displays:
% 1. Filtered signal waveform
% 2. FFT magnitude spectrum
% 3. Windowed RMS and threshold
% 4. Feature-vote count for every analysis window

    signal = double(signal(:).');

    signal = signal - mean(signal);

    %% Filter signal

    filteredSignal = fft_bandpass_filter( ...
        signal, ...
        fs, ...
        settings.analysisBandHz);

    numberOfSamples = length(filteredSignal);

    timeAxis = ...
        (0:numberOfSamples - 1) / fs;

    %% Calculate FFT

    sampleNumbers = 0:numberOfSamples - 1;

    hannWindow = 0.5 - ...
        0.5 * cos( ...
            2 * pi * sampleNumbers / ...
            max(numberOfSamples - 1, 1));

    windowedSignal = ...
        filteredSignal .* hannWindow;

    spectrum = fft(windowedSignal);

    numberPositiveBins = ...
        floor(numberOfSamples / 2) + 1;

    positiveSpectrum = ...
        spectrum(1:numberPositiveBins);

    frequencyAxis = ...
        (0:numberPositiveBins - 1) * ...
        fs / numberOfSamples;

    magnitudeSpectrum = ...
        abs(positiveSpectrum) / numberOfSamples;

    %% Calculate window feature votes

    rmsFlag = ...
        windowFeatures.RMS >= thresholds.rms;

    energyRatioFlag = ...
        windowFeatures.EnergyRatio >= ...
        thresholds.energyRatio;

    spectralCentroidFlag = ...
        windowFeatures.SpectralCentroid >= ...
        thresholds.spectralCentroid;

    voteCount = ...
        double(rmsFlag) + ...
        double(energyRatioFlag) + ...
        double(spectralCentroidFlag);

    %% Plot results

    figure('Name', 'Example Signal Diagnostics');

    subplot(4, 1, 1);

    plot(timeAxis, filteredSignal);

    xlabel('Time (seconds)');
    ylabel('Amplitude');

    title( ...
        "Filtered Signal: " + signalLabel);

    grid on;

    subplot(4, 1, 2);

    plot( ...
        frequencyAxis, ...
        magnitudeSpectrum);

    hold on;

    xline( ...
        settings.leakBandHz(1), ...
        '--', ...
        'Leak Band Start');

    xline( ...
        settings.leakBandHz(2), ...
        '--', ...
        'Leak Band End');

    xlim([0, settings.analysisBandHz(2)]);

    xlabel('Frequency (Hz)');
    ylabel('Magnitude');
    title('FFT Magnitude Spectrum');
    grid on;

    subplot(4, 1, 3);

    plot( ...
        windowFeatures.StartTime, ...
        windowFeatures.RMS, ...
        '-o');

    hold on;

    yline( ...
        thresholds.rms, ...
        '--', ...
        'RMS Threshold');

    xlabel('Window Start Time (seconds)');
    ylabel('RMS');
    title('Windowed RMS');
    grid on;

    subplot(4, 1, 4);

    stairs( ...
        windowFeatures.StartTime, ...
        voteCount, ...
        'LineWidth', ...
        1.2);

    hold on;

    yline( ...
        thresholds.minimumFeatureVotes, ...
        '--', ...
        'Positive Window Threshold');

    xlabel('Window Start Time (seconds)');
    ylabel('Feature Votes');
    ylim([-0.2, 3.2]);

    title('Windowed Feature Voting');
    grid on;
end